RazorAuth/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RazorAuth.ViewModels;

public class LoginViewModel
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    public bool RememberMe { get; set; }
}

RazorAuth/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RazorAuth.ViewModels;

public class RegisterViewModel
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string? Password { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [Compare(nameof(Password), ErrorMessage = "Passwords don't match")]
    public string? ConfirmPassword { get; set; }
}

RazorAuth/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorAuth.ViewModels;

namespace RazorAuth.Pages.Account;

public class Login : PageModel
{
    private readonly SignInManager<IdentityUser> _signInManager;

    [BindProperty] public LoginViewModel ViewModel { get; set; }

    public Login(SignInManager<IdentityUser> signInManager)
    {
        _signInManager = signInManager;
    }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync(string? returnUrl = null)
    {
        if (ModelState.IsValid)
        {
            var result =
                await _signInManager.PasswordSignInAsync(ViewModel.Email, ViewModel.Password, ViewModel.RememberMe,
                    false);

            if (result.Succeeded)
            {
                if (string.IsNullOrEmpty(returnUrl) || returnUrl.Equals("/"))
                {
                    return RedirectToPage("/Index");
                }
                else
                {
                    return RedirectToPage(returnUrl);
                }
            }
        }

        ModelState.AddModelError("", "Username or password incorrect");

        return Page();
    }
}

RazorAuth/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorAuth.Pages.Account;

public class Logout : PageModel
{
    private readonly SignInManager<IdentityUser> _signInManager;

    public Logout(SignInManager<IdentityUser> signInManager)
    {
        _signInManager = signInManager;
    }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostLogoutAsync()
    {
        await _signInManager.SignOutAsync();

        return RedirectToPage("/Index");
    }

    public IActionResult OnPostDontLogout()
    {
        return RedirectToPage("/Index");
    }
}

RazorAuth/Pages/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorAuth.ViewModels;

namespace RazorAuth.Pages;

public class Register : PageModel
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly SignInManager<IdentityUser> _signInManager;
    
    [BindProperty]
    public RegisterViewModel ViewModel { get; set; }

    public Register(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ModelState.IsValid)
        {
            var user = new IdentityUser
            {
                UserName = ViewModel.Email,
                Email = ViewModel.Email
            };

            var result = await _userManager.CreateAsync(user, ViewModel.Password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);
                return RedirectToPage("/Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        return Page();
    }
}

RazorAuth/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorAuth.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

RazorAuth/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorAuth.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

RazorAuth/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorAuth.Pages;

[Authorize]
public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

RazorAuth/Pages/Account/Login.cshtml
@page
@model RazorAuth.Pages.Account.Login

@{
    ViewData["Title"] = "Login";
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12  col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="ViewModel.Email">Email Address</label>
                    <input type="text" asp-for="ViewModel.Email" class="form-control"/>
                    <span asp-validation-for="ViewModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="ViewModel.Password">Password</label>
                    <input type="password" asp-for="ViewModel.Password" class="form-control"/>
                    <span asp-validation-for="ViewModel.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="ViewModel.RememberMe" class="form-check-input"/>
                    <label class="form-check-label" asp-for="ViewModel.RememberMe">Remember Me?</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

RazorAuth/Pages/Account/Logout.cshtml
@page
@model RazorAuth.Pages.Account.Logout

@{
    ViewData["Title"] = "Logout";
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12  col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>>
        </div>
    </div>
</form>

RazorAuth/Pages/Account/Register.cshtml
@page
@model RazorAuth.Pages.Register

@{
    ViewData["Title"] = "Register";
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12  col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="ViewModel.Email">Email Address</label>
                    <input type="text" asp-for="ViewModel.Email" class="form-control"/>
                    <span asp-validation-for="ViewModel.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="ViewModel.Password">Password</label>
                    <input type="password" asp-for="ViewModel.Password" class="form-control"/>
                    <span asp-validation-for="ViewModel.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="ViewModel.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="ViewModel.ConfirmPassword" class="form-control"/>
                    <span asp-validation-for="ViewModel.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

RazorAuth/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorAuth/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorAuth</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>


<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">RazorAuth</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" hidden="@(!_signInManager.IsSignedIn(User))" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>

                </ul>

                @{
                    if (_signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav d-flex justify-content-end">
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-page="/Account/Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <li class="nav-item">
                                <a asp-page="/Account/Login" class="btn btn-primary">Login</a>
                            </li>
                            <li class="nav-item">
                                <a asp-page="/Account/Register" class="btn">Register</a>
                            </li>
                        </ul>
                    }
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - RazorAuth - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>